### ISSUE TITLE
Cannot create super user

### ISSUE THREAD

**Issue by lbrossault** [thalesgroup-cert/Watcher#45]
**Describe the bug**
After installation (on Ubuntu 20.04), when I try to define a super user using: 
```
docker-compose down
docker-compose run watcher bash
python manage.py createsuperuser
```
I have following error message: `django.db.utils.ProgrammingError: (1146, "Table 'db_watcher.auth_user' doesn't exist")`

**To Reproduce**
1. Type: docker-compose down
2. Type: docker-compose run watcher bash

**Expected behavior**
I cannot define superuser (but can connect to web portal)

**Screenshots**
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 100, in handle
    default_username = get_default_username(database=database)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/__init__.py", line 141, in get_default_username
    auth_app.User._default_manager.db_manager(database).get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'db_watcher.auth_user' doesn't exist")
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Ubuntu 20.04.2 LTS
 - Browser Firefox 78.11esr

**Comment by Felix83000** [comment]
Hello,

I think that there was an issue when you initiate the mysql database.

May you perform the followed command lines:
```
docker-compose down
docker remove volume db_data
docker-compose up 
````

After doing the `docker-compose up` you need to wait for this message to show on the log after doing CTRL-C:
```
watcher          | db_watcher is up, starting Watcher.
watcher          | Performing system checks...
watcher          | 
watcher          | System check identified no issues (0 silenced).
watcher          | October 08, 2020 - 10:28:02
watcher          | Django version 3.1.1, using settings 'watcher.settings'
watcher          | Starting development server at http://0.0.0.0:9002/
watcher          | Quit the server with CONTROL
```

Then, do the migration and after the create superuser command.

Keep me posted.
Thanks

**Comment by lbrossault** [comment]
Many thanks for your quick response.

See errors:
```
root@cha-inn-watch:/opt/Watcher# **docker-compose down**
Removing watcher       ... done
Removing searx         ... done
Removing searx-checker ... done
Removing rss-bridge    ... done
Removing db_watcher    ... done
Removing network watcher_default
root@cha-inn-watch:/opt/Watcher# **docker list volumes**
docker: 'list' is not a docker command.
See 'docker --help'
root@cha-inn-watch:/opt/Watcher# **docker volume rm watcher-project_db_data**
Error: No such volume: watcher-project_db_data
```



```
db_watcher       | 2021-06-28T19:52:25.689143Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
watcher          | db_watcher is up, starting Watcher.
searx exited with code 1
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
watcher          | Watching for file changes with StatReloader
watcher          | Performing system checks...
watcher          |
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
searx exited with code 1
watcher          | System check identified no issues (0 silenced).
watcher          |
watcher          | You have 73 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, data_leak, dns_finder, knox, sessions, site_monitoring, threats_watcher.
watcher          | Run 'python manage.py migrate' to apply them.
watcher          | June 28, 2021 - 21:52:31
watcher          | Django version 3.2, using settings 'watcher.settings'
watcher          | Starting development server at http://0.0.0.0:9002/
watcher          | Quit the server with CONTROL-C.
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
searx exited with code 1
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
searx exited with code 1
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
searx exited with code 1
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
searx exited with code 1
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
searx exited with code 1
watcher          | 2021-06-28 21:54:00.002935 - CRON TASK : Suspicious Website Monitoring
watcher          | Job "monitoring_check (trigger: cron[day_of_week='mon-sun', minute='*/6'], next run at: 2021-06-28 22:00:00 CEST)" raised an exception
watcher          | Traceback (most recent call last):
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
watcher          |     return self.cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
watcher          |     return self.cursor.execute(query, args)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
watcher          |     res = self._query(query)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
watcher          |     db.query(q)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
watcher          |     _mysql.connection.query(self, query)
watcher          | MySQLdb._exceptions.ProgrammingError: (1146, "Table 'db_watcher.site_monitoring_site' doesn't exist")
watcher          |
watcher          | The above exception was the direct cause of the following exception:
watcher          |
watcher          | Traceback (most recent call last):
watcher          |   File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
watcher          |     retval = job.func(*job.args, **job.kwargs)
watcher          |   File "/app/Watcher/site_monitoring/core.py", line 74, in monitoring_check
watcher          |     for site in sites:
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
watcher          |     self._fetch_all()
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
watcher          |     self._result_cache = list(self._iterable_class(self))
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
watcher          |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
watcher          |     cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
watcher          |     return super().execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
watcher          |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
watcher          |     return executor(sql, params, many, context)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
watcher          |     return self.cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
watcher          |     raise dj_exc_value.with_traceback(traceback) from exc_value
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
watcher          |     return self.cursor.execute(sql, params)
watcher          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
watcher          |     return self.cursor.execute(query, args)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
watcher          |     res = self._query(query)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
watcher          |     db.query(q)
watcher          |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
watcher          |     _mysql.connection.query(self, query)
watcher          | django.db.utils.ProgrammingError: (1146, "Table 'db_watcher.site_monitoring_site' doesn't exist")
```

**Comment by lbrossault** [comment]
After `python manage.py migrate`, it worked fine. I have created super user using `python manage.py createsuperuser` command.

Thanks for your support !
