### ISSUE TITLE
searx dontainer restart always

### ISSUE THREAD

**Issue by lbrossault** [thalesgroup-cert/Watcher#46]
**Describe the bug**
I'm using latest Watcher version (retrieve yesterday from GitHub). 

**To Reproduce**
1. Launch `docker-compose up` using proxy defined in `.env`

**Expected behavior**

**Screenshots**
```
root@vm:/opt/Watcher# **docker ps**
CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                          PORTS                                                  NAMES
7e6c9c22e48f   felix83000/watcher:latest         "sh -c '/tmp/wait-fo…"   56 minutes ago   Up 2 minutes                    0.0.0.0:443->9002/tcp, :::443->9002/tcp                watcher
398a095b5489   searx/searx-checker               "/sbin/tini -- /usr/…"   16 hours ago     Up 2 minutes                                                                           searx-checker
07bb317190bf   searx/searx:0.18.0-341-ae0b621e   "/sbin/tini -- /usr/…"   16 hours ago     **Restarting (1) 28 seconds ago**                                                          searx
9cfdc6e5d94b   rssbridge/rss-bridge:latest       "docker-php-entrypoi…"   16 hours ago     Up 2 minutes                    80/tcp                                                 rss-bridge
44046aff6a26   mysql:latest                      "docker-entrypoint.s…"   16 hours ago     Up 2 minutes                    33060/tcp, 0.0.0.0:3307->3306/tcp, :::3307->3306/tcp   db_watcher
```

**Desktop (please complete the following information):**
 - OS:Ubuntu 20.04
 - Browser Firefox 78.22esr

**Additional context**
From Watcher page we don't have tweet information
From Data Leak page, we don't have any information
[watcher.txt](https://github.com/thalesgroup-cert/Watcher/files/6733437/watcher.txt)

**Comment by Felix83000** [comment]
Hi,

From Watcher page we don't have tweet information
Did you populate your database?(Like described in the documentation)
```
docker-compose down 
docker-compose run watcher bash
python manage.py populate_db 
```

For the Searx container did you create the Searx folder at the project root? (Like described in the documentation)

Regards.

**Comment by lbrossault** [comment]
Hello,

Same issue:
```
watcher          | System check identified no issues (0 silenced).
watcher          | June 30, 2021 - 08:21:47
watcher          | Django version 3.2, using settings 'watcher.settings'
watcher          | Starting development server at http://0.0.0.0:9002/
watcher          | Quit the server with CONTROL-C.
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
```

```
searx-checker    | Traceback (most recent call last):
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
searx-checker    |     resp = conn.urlopen(
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
searx-checker    |     retries = retries.increment(
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
searx-checker    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
searx-checker    | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.10.10.3', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88ce1a4100>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
searx-checker    |
searx-checker    | During handling of the above exception, another exception occurred:
searx-checker    |
searx-checker    | Traceback (most recent call last):
searx-checker    |   File "./checker/checker.py", line 228, in <module>
searx-checker    |     main(args.url, args.o)
searx-checker    |   File "./checker/checker.py", line 209, in main
searx-checker    |     config = get_config(instance_url)
searx-checker    |   File "./checker/checker.py", line 92, in get_config
searx-checker    |     resp = requests.get(url + CONFIG_API_ENDPOINT)
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
searx-checker    |     return request('get', url, params=params, **kwargs)
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
searx-checker    |     return session.request(method=method, url=url, **kwargs)
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
searx-checker    |     resp = self.send(prep, **send_kwargs)
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
searx-checker    |     r = adapter.send(request, **kwargs)
searx-checker    |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
searx-checker    |     raise ConnectionError(e, request=request)
searx-checker    | requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.10.10.3', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88ce1a4100>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
searx-checker    | Sleep 86285 seconds
searx            | searx version 0.18.0-341-ae0b621e
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 10.10.10.3:8080
searx            | realpath() of /etc/searx/uwsgi.ini failed: Permission denied [core/utils.c line 3654]
```

Home directory of the project:
```
drwxr-x--- 7 root root    4096 Jun 29 12:36 ./
drwxr-xr-x 8 root root    4096 Jun 28 14:01 ../
-rw-r----- 1 root root    1406 Jun 29 11:34 .env
drwxr-x--- 8 root root    4096 Jun 28 13:56 .git/
drwxr-x--- 4 root root    4096 Jun 28 13:56 .github/
-rwxr-x--- 1 root root    5510 Jun 28 13:56 .gitignore*
-rw-r----- 1 root root   34523 Jun 28 13:56 LICENSE
-rw-r----- 1 root root    4908 Jun 28 13:56 README.md
drwxr-x--- 2 root root    4096 Jun 29 12:17 Rss-bridge/
drwxr-x--- 3 root root    4096 Jun 28 13:56 Searx/
drwxr-x--- 5 root root    4096 Jun 28 13:56 Watcher/
-rwxr-x--- 1 root root    3414 Jun 28 18:53 docker-compose.yml*
```

**Comment by lbrossault** [comment]
Note: I use proxy (defined in .env file) but for each pattern defined in keywords to monitor I can see following error message:
```
watcher          | 2021-06-30 08:30:06.174477 - Querying Searx for:  "password"
watcher          | 2021-06-30 08:30:09.246290 -  HTTPConnectionPool(host='10.10.10.3', port=8080): Max retries exceeded with url: /?q=%22password%22&engines=gitlab%2Cgithub%2Cbitbucket%2Capkmirror%2Cgentoo%2Cnpm%2Cstackoverflow%2Choogle&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15c0e8e940>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by Felix83000** [comment]
Hi,

I think that is a permission Issue.

You need to grant the right permissions on all your Watcher, Searx and Rss-Bridge folders.

Best regards,
