### ISSUE TITLE
Twitter Feeds are no longer actualised using latest docker build

### ISSUE THREAD

**Issue by anykeypress** [thalesgroup-cert/Watcher#60]
The Twitter Feeds are no longer refreshed using the latest docker build.

Error entry from the in the rss-bridge containers log:

[Mon Jan 10 16:31:07.478972 2022] [php7:notice] [pid 22] [client x.x.x.x:xxxxx] Exception: Could not parse guest token in /app/lib/error.php:24\nStack trace:\n#0 /app/lib/error.php(42): returnError()\n#1 /app/bridges/TwitterBridge.php(551): returnServerError()\n#2 /app/bridges/TwitterBridge.php(584): TwitterBridge->getApiKey()\n#3 /app/bridges/TwitterBridge.php(241): TwitterBridge->getApiContents()\n#4 /app/actions/DisplayAction.php(135): TwitterBridge->collectData()\n#5 /app/index.php(38): DisplayAction->execute()\n#6 {main},
X.X.X.X - - [10/Jan/2022:16:31:06 +0100] "GET /?action=display&bridge=Twitter&context=By+username&u=CSAsingapore&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss HTTP/1.1" 200 1487 "-" "python-requests/2.26.0"

IP are redacted

After testing the Twitter feed at https://wtf.roflcopter.fr/rss-bridge/#bridge-Twitter it appears to be an rss-bridge issue, but I'm not 100% sure...

**Comment by anykeypress** [comment]
Closing this as looking at the rss-bridge page [https://github.com/RSS-Bridge/rss-bridge/issues/2407](url) it seems to be coming from there.
